TTNX_API_KEY = 'TTNX_API_KEY'

TTNX_AVG_SQUEEZE = "squeeze"
TTNX_AVG_SENTENCE = "sentence"
TTNX_AVG_TRUNCATE = "truncate"
TTNX_AVG_NONE = "none"
TTNX_WEIGHT_NEG_LIN = "neg_lin"
TTNX_WEIGHT_NEG_EXP = "neg_exp"

TTNX_DEFAULT_AVG = TTNX_AVG_SQUEEZE
TTNX_DEFAULT_WEIGHT = TTNX_WEIGHT_NEG_LIN
